# Generated by Django 2.1.5 on 2019-03-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistantHearingGroups',
            new_name='DistantHearingGroup',
        ),
    ]
