# explanation for distant analysis
general_explanation = "Analysis results can viewed for different aspects of music, such as chords, pitches, key or ambitus. In many of the graphs, the predefined groups can be differed by the different colors. By clicking on the legend, a group can be disabled and enabled again, which makes it possible to focus on subgroups. Just hover over the charts to few more detailed information like the exact numbers."
chords_explanation = "Chords offers three different types of visualization, all displayed in a bar chart. There is the roman numeral chord count, which categorizes chords according to their function in roman numeral analysis, the chord root count, which shows the number of occurrences of each root and the chord quality count, which displays the number of occurrences of each quality of the underlying triad of a triad or seventh. The quality can either be major, minor, augmented or diminshed. In case a clear answer cannot be determined, the chord falls into the category 'other'."
pitches_explanation = "Pitches offer three different types of analysis results. The octave count shows how many pitches were in a certain octave, the pitch name count shows the number of occurrences for different pitches, and the pitch name count with octave combines the two and provides information on the number of occurrences of pitches of a certain name within a certain octave."
durations_explanation = "Duration analysis takes a look at the durations of notes and rests separately, and shows histograms for the name and number of the durations with the unit being quarter notes. Another chart treats notes and rests the same, and shows a histogram of durations of note and rest elements. Finally, the last chart juxtaposes the total durations of silence (rests) and sound (notes) in a group of music pieces."
key_explanation = "Key analysis routines are a variation of the algorithm developed by Carol Krumhansl and Mark A. Schmuckler called probe-tone key finding. The charts present the number of the times a key occured as the most probable one per group. Additional line charts show the four most probable keys identified for each music piece, together with their probabilities, in different graphs per group."
ambitus_explanation = "The ambitus is the range, or the distance between the highest and lowest note. It is visualised by two different visualizations. First, there is the range chart. The x-axis shows all the possible notes, while the y-axis isn’t used or needed and therefore doesn't have a value. The colored bar starts at the lowest pitch and ends at the highest pitch. The different colours stand for the different music pieces. Each group has it’s own diagram. The box plot shows the number of semitones, the maximum, medium and minimum as well as the upper (75%) and lower (25%) quartile."

distant_hearing_explanations = {"general": general_explanation,
                                "chords": chords_explanation,
                                "pitches": pitches_explanation,
                                "durations": durations_explanation,
                                "key": key_explanation,
                                "ambitus": ambitus_explanation
                                }
